lab5/myimgur/images/urls.py
from django.urls import path
from .views import image_list, detail
app_name = "images"
urlpatterns = [
    path('', image_list, name = "list"),
    path('<int:image_id>/', detail, name = "detail"),
]

lab5/myimgur/myimgur/urls.py
from django.contrib import admin
from django.urls import path, include 
from images.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name = "home"),
    path('slike/', include('images.urls')),
]

lab5/myimgur/images/models.py
from django.db import models

class Image(models.Model):
    title = models.CharField(max_length= 128)
    url = models.CharField(max_length=512)
    pub_date = models.DateTimeField()
    
    def __str__(self):
        return f"{self.id}: {self.title}"

lab5/myimgur/images/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Image

# Create your views here.
def home(request):
    context = {}
    return render(request, 'images/home.html', context)

def image_list(request):
    images = Image.objects.all()
    context = {
        'images' : images,
    }
    return render(request, 'images/list.html', context)

def detail(request, image_id):
    image = get_object_or_404(Image, pk = image_id)
    context = {
        'image' : image,
    }
    return render(request, 'images/detail.html', context)

lab5/myimgur/images/templates/images/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <a href="/">MyImgur</a>
        <a href="{% url 'images:list' %}">MyImages</a>
    </div>
    <h1>Welcome to MyImgur</h1>
    {% block content %}
    {% endblock content %}
</body>
</html>

lab5/myimgur/images/templates/images/detail.html
{% extends 'images/base.html' %}
{% block content %}
    <h1>{{image.title}}</h1>
    <p>{{image.pub_date}}</p>
    <img src="{{image.url}}", style ="width: 600px;">
{% endblock content %}

lab5/myimgur/images/templates/images/home.html
{% extends 'images/base.html' %}
{% block content %}
    <a href="{% url 'images:list' %}">Vidi nase slike</a>
{% endblock content %}

lab5/myimgur/images/templates/images/list.html
{% extends 'images/base.html' %}
{% block content %}
    {% for image in images %}
        <h3>
            <a href="{% url 'images:detail' image.id %}">{{ image.title }}</a>
        </h3>
        <p><small>{{ image.pub_date }}</small></p>
        <img src ="{{ image.url }}" style = "width: 150px;">
    {% endfor %}
{% endblock content %}